######################################################################
# Automatically generated by qmake (3.0) ?? 9? 16 00:15:29 2015
######################################################################

TEMPLATE = app
TARGET = GPRS
INCLUDEPATH += .

# Input
HEADERS += gprs.h
SOURCES += gprs.c
